# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

[[main]]
  name = "Koti"
  url = "/"
  weight = 10

[[main]]
  name = "Uutiset"
  url = "/uutiset"
  weight = 20

[[main]]
  name = "Tiimi"
  url ="/people"
  weight = 30

[[main]]
  name = "Helluradio"
  url ="/radio"
  weight = 31

[[main]]
  name = "Tapahtumat"
  url ="/event"
  weight = 40

[[main]]
  name = "Meistä"
  url = "/meista"
  weight = 45

[[main]]
  name = "Ota yhteyttä"
  url = "/contact"
  weight = 50